name: CI + Build + Push to ECR

on:
 pull_request:
  branches: [ main ]
  types: [opened, synchronize, reopened]

 push:
  branches: [ main ]

env:
 IMAGE_NAME: tiny-health-app

jobs:
 ci-build-push:
  runs-on: ubuntu-latest


  steps:
   - name: Checkout repository
     uses: actions/checkout@v4

   - name: Set image tag
     run: |
      if [ "${{ github.event_name }}" = "pull_request" ]; then
        echo "IMAGE_TAG=pr-${{ github.event.number }}" >> $GITHUB_ENV
      else
        echo "IMAGE_TAG=latest" >> $GITHUB_ENV
      fi

   - name: Set up Python
     uses: actions/setup-python@v4
     with:
      python-version: "3.12"

   - name: Run tests
     run: python -m unittest discover -s tests -v

   - name: Run Trivy scan
     uses: aquasecurity/trivy-action@v0.20.0
     with:
      scan-type: fs
      scan-ref: .
      severity: HIGH,CRITICAL
      exit-code: 1

   - name: Configure AWS credentials
     uses: aws-actions/configure-aws-credentials@v4
     with:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-region: ${{ secrets.AWS_REGION }}

   - name: Login to Amazon ECR
     uses: aws-actions/amazon-ecr-login@v2

   - name: Create ECR repo if not exists
     run: |
      aws ecr describe-repositories --repository-names $IMAGE_NAME || \
      aws ecr create-repository --repository-name $IMAGE_NAME

   - name: Build Docker image
     run: docker build -t $IMAGE_NAME .

   - name: Tag image
     run: |
      docker tag $IMAGE_NAME:latest \
      ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/$IMAGE_NAME:$IMAGE_TAG

   - name: Push image
     run: |
      docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/$IMAGE_NAME:$IMAGE_TAG
